### ISSUE TITLE
Returning the address of an array element

### ISSUE THREAD

**Issue by Mahmohsen** [verifast/verifast#102]
In a function like the following, VeriFast complains that "Taking the address of this expression is not supported". The only way to go around this is to use pointer arithmetic, but it will be nice if I can just get the address like in the following function:

```c
int array[3];
int test()
//@requires true;
//@ensures true;
{
	int* y = &array[2];
	return *y;
}
```

**Comment by btj** [comment]
Fixed by 5748fac25dd05a3f7dce5b31cfff64ea9e01cda0
