### ISSUE TITLE
Unsupported syntax of function pointers

### ISSUE THREAD

**Issue by aguirguis** [verifast/verifast#112]
When I try to define the function pointer this way:
```c
typedef int (*fptr_def)(int x);
```
and define some function that follows this signature: `int cb(int x);`
and then use it this way:
```c
register_callback(cb);
```
verifast complains!
However, doing it this way:
```c
typedef int fptr_def(int x);          //notice the removed star"*"
register_callback(&cb);
```
it works!
So, why don't you support the first-mentioned syntax?

Thanks

**Comment by btj** [comment]
No particular reason. VeriFast's C parser is hand-written from scratch, and there are many valid C patterns that are not yet supported. But feel free to leave this issue open; maybe one day we'll get around to adding support for this syntax.

Note 1: applying VeriFast always involves a lot of annotation work. It also always involves some transformation of the C code to get it accepted by the VeriFast parser. However, in comparison to adding the annotations, the transformation is not much work.

Note 2: it's open source; feel free to implement this yourself! :-)

**Comment by eleehiga** [comment]
@btj Hi if you guys could please implement this type of function pointer declaration like `typedef int (*fptr_def)(int x);` that would be great.

**Comment by btj** [comment]
This turned out to be easier than I had thought.

**Comment by eleehiga** [comment]
@btj  From here: https://stackoverflow.com/questions/840501/how-do-function-pointers-in-c-work. The following code:
```c
int addInt(int n, int m) {
	    return n+m;
}

typedef int (*myFuncDef)(int x, int y);
	//@ requires true;
	//@ ensures true;

int test(int n) 
	//@ requires true;
	//@ ensures true;
{
    myFuncDef functionPtr = &addInt;
    sum = (*functionPtr)(2, 3);
    return;
}
```
has an error message at the `&` sign which says: `Type mismatch. Actual: void * *. Expected: myFuncDef *.` Was wondering if you please support this type of use.

**Comment by eleehiga** [comment]
@btj Was wondering if you could please also implement not needing to declare a variable name for function pointer declarations. For example to support `typedef int (*myFuncDef)(int x, int y);` as well as `typedef int (*myFuncDef)(int, int);`.

**Comment by btj** [comment]
@eleehiga Did you get notified of my commit?

**Comment by eleehiga** [comment]
@btj Thank you for implementing this change and I did not get notified of your commit
