### ISSUE TITLE
Is there a way to list all the "unsatisfied requirement"s with verifast?

### ISSUE THREAD

**Issue by necto** [verifast/verifast#126]
Currently if it does not encounter a proof of a lemma, it fails with 
> Module '../lib/expirator.vfmanifest': unsatisfied requirement './../lib/coherence.h#kkeeperp_erase_one'.

And stops further linking. Is there a way to list all such unproven lemmas?

**Comment by necto** [comment]
An hackish adhock solution:

```
verifast -emit_vfmanifest ... <source files>
mkdir manifests
find . -name '*.vfmanifest' -exec cp -t manifests/ '{}' \;
cd manifests
cat * | grep requires | grep -v 'CRT/' | sed 's/.requires //' | sort -u > requires
cat * | grep provides | sed 's/.provides //' | sort -u > provides
comm -23 requires provides
```

**Comment by btj** [comment]
Fixed by https://github.com/verifast/verifast/commit/ea3f20bcad136e381308fe455a7f9b785ac08d2a
