### ISSUE TITLE
Verifast does not support the & sign in the function contracts

### ISSUE THREAD

**Issue by Mahmoud-Ammar** [verifast/verifast#132]
Considering that I have a struct:
typedef struct{
  sha1_ctx_t a; 
  sha1_ctx_t b;
} hmac_sha1_ctx_t;

Where sha1_ctx_t is another struct: 
typedef struct {
	uint32_t h[5];
	uint64_t length;
} sha1_ctx_t;

and I have a predicate named: state_pred that starts as first parameter with a pointer to sha1_ctx_t.

If I have :  hmac_sha1_ctx_t *s, the following expressions are not supported in verifast to be used in the function contracts:

&(s->a) |-> ?p
(s->a) |-> ?P &*& state_pred(&p,_,_,_,_,_,_)
state_pred(&(s->a),_,_,_,_,_,_)

Is it possible to support any of them? If not, what are the alternative solutions? 

Thanks!

**Comment by btj** [comment]
The first two expressions are incorrect, but the third one should work, and does indeed work on my machine. I am running VeriFast 18.02.

**Comment by btj** [comment]
Closing; please reopen if your issue is not solved.
