### ISSUE TITLE
Value of variable unknown after it gets assigned

### ISSUE THREAD

**Issue by elleboog** [verifast/verifast#137]
In the function inf_interval() when a variable gets assigned the value (negative) infinity, it is afterwards not known to have this value. However in the functions test_pos_inf() and test_neg_inf() this does work correctly.
The code can be found in infinity_bug.c, together with the files vf__bug_floating_point.h and bug_math.h (change the .txt extensions)
This has been tested with z3 v4.5

[bug_math.txt](https://github.com/verifast/verifast/files/2291322/bug_math.txt)
[vf__bug_floating_point.txt](https://github.com/verifast/verifast/files/2291324/vf__bug_floating_point.txt)
[infinity_bug.c.txt](https://github.com/verifast/verifast/files/2291328/infinity_bug.c.txt)

**Comment by btj** [comment]
In `result.a == -INFINITY;`, `==` should be `=`.
