### ISSUE TITLE
default colors issue on Arch Linux

### ISSUE THREAD

**Issue by sanderr** [verifast/verifast#147]
When verifying the illegal_acces.c example, the verifast IDE shows the error message as white text on a white background. This might be specific to my setup.
![verifast](https://user-images.githubusercontent.com/7672159/46736642-daefa080-cc99-11e8-8697-1a7dbdd89a81.png)

**Comment by sanderr** [comment]
On my other computer, also running Arch, this works fine. I suspect this is an issue with my setup, and has nothing to do with verifast itsself.
If anyone still wants to test this, I have created an AUR package which installs the 18.02 binary here: https://aur.archlinux.org/packages/verifast-bin/

**Comment by btj** [comment]
Another student has the same problem on Fedora Linux.

**Comment by btj** [comment]
The background is set to red [here](https://github.com/verifast/verifast/blob/master/src/vfide.ml#L735), using method `modify_base` from class [`misc_ops`](http://lablgtk.forge.ocamlcore.org/refdoc/GObj.misc_ops-c.html) implemented [here](http://git.ocamlcore.org/cgi-bin/gitweb.cgi?p=lablgtk/lablgtk.git;a=blob;f=src/gObj.ml;h=20b2163acd8a54d7bef7699c306692e0ce610d2b;hb=HEAD#l309), which calls into [here](http://git.ocamlcore.org/cgi-bin/gitweb.cgi?p=lablgtk/lablgtk.git;a=blob;f=src/gtkBase.ml;h=b52807b50eafdf0e3686b80d3c1e184e8b51f855;hb=HEAD#l114), which calls into [here](http://git.ocamlcore.org/cgi-bin/gitweb.cgi?p=lablgtk/lablgtk.git;a=blob;f=src/ml_gtk.c;h=23385cd5d3a417d49f6815702d35991e112c7e75;hb=HEAD#l348), which calls [`gtk_widget_modify_base`](https://developer.gnome.org/gtk2/2.24/GtkWidget.html#gtk-widget-modify-base).

**Comment by btj** [comment]
Two possible explanations of the behavior are that in these configurations, the `GtkEntry` does not have its own window (i.e. ``messageEntry#coerce#misc#get_flag `NO_WINDOW`` returns `true`) or that it is not considered to be in state `NORMAL`. (Unfortunately, lablgtk does not seem to expose the `gtk_widget_get_state` function.)

**Comment by sanderr** [comment]
Your response prompted me to try with another window manager / desktop environment. For me, this issue appears on xmonad and i3 (both simple window managers), but not on xfce4 (a desktop environment). I am not familiar with GTK at all, but from what I know about window managers, your first explanation seems likely. Can I test this somehow?

**Comment by btj** [comment]
See https://github.com/verifast/verifast/commit/c692101bda0db63eb03a2225220baecd925874b1 ; once the [build finishes](https://travis-ci.org/verifast/verifast/jobs/446130303) the new binary is available [here](
http://82076e0e62875f063ae8-929808a701855dfb71539d0a4342d4be.r54.cf5.rackcdn.com/verifast-nightly.tar.gz). This prints a message to the terminal if the messageEntry has no window (so run `vfide` from a terminal to see this message).

An alternative cause could be interference from a GTK theme engine. Launching `vfide` with `GTK2_RC_FILES` pointing to an empty file should disable the use of the engine:
```bash
echo > mygtkrc
GTK2_RC_FILES=mygtkrc vfide myprogram.c
```

**Comment by willempx** [comment]
Same problem on my system (Debian, xfce). `c69201` does not print a message on the terminal.  Setting `GTK2_RC_FILES` to the name of an empty file does not seem to disable the engine. However, just changing GTK2 theme (engine) in another way (e.g. xfce preferences or any GTK2 theme switcher) solves (well, workarounds) the problem. Unfortunately I won't have much time to look into this.

**Comment by btj** [comment]
So it depends on the theme (engine). Which themes/engines cause the problem and which don't?

**Comment by btj** [comment]
I can reproduce the problem by running a live "Try Fedora" session of Fedora Workstation Live x86_64 28 1.1 ISO in a VirtualBox VM. I did not change any settings. In this setup, running
```bash
gsettings get org.gnome.desktop.interface gtk-theme
```
outputs `'Adwaita'`.

**Comment by sanderr** [comment]
I have not had the time to look at `c69201` yet, so I can't comment on that, but I have run `gsettings get org.gnome.desktop.interface gtk-theme` on xmonad, i3, and xfce, and for all three it also outputs `'Adwaita'`. However, as mentioned before, I do not experience the issue on xfce.

**Comment by btj** [comment]
In the Fedora setup, running `cat /usr/share/gtk-2.0/gtkrc` produces
```
gtk-theme-name = "Adwaita"
gtk-icon-theme-name = "Adwaita"
gtk-cursor-theme-name = "Adwaita"
gtk-button-images = 0
gtk-menu-images = 0
```

**Comment by sanderr** [comment]
On my system this produces
```
gtk-icon-theme-name = "Adwaita"
gtk-theme-name = "Adwaita"
gtk-font-name = "Cantarell 11"
```

**Comment by btj** [comment]
In a standard Ubuntu 18.04 setup, `gsettings get org.gnome.desktop.interface gtk-theme` produces `'Ambiance'`. But running `gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita'` changes the theme and causes the white-on-white problem.

**Comment by sanderr** [comment]
Alas, the opposite: running `gsettings set org.gnome.desktop.interface gtk-theme 'Ambiance'` does not solve the issue for me.

**Comment by btj** [comment]
But changing the theme through a settings dialog probably would fix the problem?

**Comment by sanderr** [comment]
Great, thanks. I appear to not have `Ambiance` installed, that might explain why that did not work for me. Thanks for looking into this.

**Comment by btj** [comment]
Note: Apparently, Adwaita is the successor of Raleigh as the default GTK+ theme: https://blogs.gnome.org/mclasen/2014/06/13/a-new-default-theme-for-gtk/

**Comment by btj** [comment]
[A very relevant blog post.](https://www.omgubuntu.co.uk/2018/10/on-gtk-themes-broken) One thing it mentions is that Ubuntu's default theme will change in 18.10 from Ambiance to Yaru, an Adwaita variant.

**Comment by btj** [comment]
On Ubuntu 18.04, after causing the problem to appear by running `gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita'`, running `vfide` with `GTK_DATA_PREFIX=` fixes the issue by disabling all theming, which produces the built-in Raleigh look:
```bash
GTK_DATA_PREFIX= bin/vfide
```
My plan is to set this variable inside `vfide` at startup time by default (on Linux), unless overridden by a `-use-platform-gtk-theme` command-line option.
