### ISSUE TITLE
unsigned number overflow not detected

### ISSUE THREAD

**Issue by whitebird** [verifast/verifast#15]
**Steps:** Create file with following code and let Verifast verify
**Expected result:** Detection of the overflow
**Actual result:** 0 errors found (2 statements verified)

Tested with Verifast 15.11

```c
void main()
//@ requires true;
//@ ensures true;
{
	unsigned char number = 255;
	number = (unsigned char)((int)(number) + 1);
}
```

**Comment by btj** [comment]
Was fixed by 11634021a59dff96e5be964639951255457699a1.
