### ISSUE TITLE
Verification of undefined behavior w/ right shift

### ISSUE THREAD

**Issue by VisualizeTheWorld** [verifast/verifast#156]
Verifast verifies the following program, despite right shifts by negative values or more than the bit width of the promoted left operand being undefined behavior (as per C99 spec, section 6.5.7.3).

```
int main() //@ :main() 
  //@requires true;
  //@ensures true;
{
  int x = 1 >> -1;
  int y = 1 >> 100;
  return 0;
}
```

**Comment by btj** [comment]
Fixed by 4badf8e6a7ac9fd977c4d96b6f1e217840903ccd and 98519a36c687a7bf576d660638a175ac3a2b44ad
