### ISSUE TITLE
Can not prove A <= A * (B-C) which B-C is greater than 1

### ISSUE THREAD

**Issue by wgy0831** [verifast/verifast#172]
I used a lemma named split_characters_chunk which is used in tutorial and I changed it from characters to chars.
```
lemma void split_characters_chunk(char *start, size_t i, size_t count)
requires chars(start, count, _) &*& 0 <= i &*& i <= count;
ensures chars(start, i, _) &*& chars(start + i, count - i, _);
{
	if (i == 0) {
		close chars(start, 0, _);
	} else {
		open chars(start, count, _);
		split_characters_chunk(start + 1, i - 1, count - 1);
		close chars(start, i, _);
	}
}
```
I used it in this way:
`//@ split_characters_chunk(q->write_ptr, q->msg_size, q->msg_size * (q->max_msgs - wp));`
and I've got these useful assumptions:
0 < msg_size
0 <= wp
1 <= (max_msgs - wp)
and heap chunks:
chars(write_ptr, (msg_size * (max_msgs - wp)), cons(c, cs0))
k_msgq_max_msgs(q, max_msgs)
k_msgq_msg_size(q, msg_size)
k_msgq_write_ptr(q, write_ptr)
It told me that it cannot prove the 'i <= count' condition which i is msg_size and count is msg_size * (max_msgs - wp). I have no idea with it. Did I forget other assumptions it needed?

**Comment by jpdoyle** [comment]
Redux doesn't have a lot of knowledge about multiplication out of the box, but you can prove many important things as lemmas.

In your case: `mul_mono_r(msg_size, max_msgs - wp)` should cover it, using `mul_mono_r` as proved in https://github.com/verifast/verifast/blob/dff084c8a4564ca41debff9282e4db0f278e0a0f/tests/longlong.c#L15

**Comment by wgy0831** [comment]
> Redux doesn't have a lot of knowledge about multiplication out of the box, but you can prove many important things as lemmas.
> 
> In your case: `mul_mono_r(msg_size, max_msgs - wp)` should cover it, using `mul_mono_r` as proved in
> 
> https://github.com/verifast/verifast/blob/dff084c8a4564ca41debff9282e4db0f278e0a0f/tests/longlong.c#L15

It works! Thank you very much!!!!!! :)

**Comment by wgy0831** [comment]
I'm sorry to reopen this issue. Now I need to prove B > C with assumptions : AB > AC and A > 0, which is a inverse proposition of above problem, and I still have no idea. I find the tests folder and find nothing to deal with it. :(

**Comment by btj** [comment]
Try proving it by contradiction:
```c
if (B <= C) {
    mul_mono_r(A, B, C); // gives you AB <= AC
    assert false;
}
```

**Comment by wgy0831** [comment]
> Try proving it by contradiction:
> 
> ```c
> if (B <= C) {
>     mul_mono_r(A, B, C); // gives you AB <= AC
>     assert false;
> }
> ```

I tried and got the error:
Assertion might not hold:  false
I wonder if I wrote in a wrong way. :(
Cause B is a bounded variable that isn't able to be seem outside annotations, I wrote the code below:
```
/*@
	if (wp <= q->max_msgs) {
		mul_mono_r(q->msg_size, wp, q->max_msgs);
		assert false;
	}
@*/
```

**Comment by btj** [comment]
The following verifies:
```c
/*@

lemma void mul_mono_strict_conv_r(int a, int b, int c)
    requires 0 < a &*& a * b < a * c;
    ensures b < c;
{
    if (c <= b) {
        mul_mono_l(c, b, a);
        assert false;
    }
}

@*/
```
Make sure you are using a recent version of VeriFast.

**Comment by wgy0831** [comment]
> The following verifies:
> 
> ```c
> /*@
> 
> lemma void mul_mono_strict_conv_r(int a, int b, int c)
>     requires 0 < a &*& a * b < a * c;
>     ensures b < c;
> {
>     if (c <= b) {
>         mul_mono_l(c, b, a);
>         assert false;
>     }
> }
> 
> @*/
> ```
> 
> Make sure you are using a recent version of VeriFast.

Finally it works.  Thanks a lot!
