### ISSUE TITLE
Suggestion: Automatically avoid forks due to short-circuiting operators

### ISSUE THREAD

**Issue by SolalPirelli** [verifast/verifast#180]
I was investigating some code that verified slowly, which turned out to be caused by excessive forking from code like `assume(x == a || x == b);`. Because this kind of assume was occurring N times at the beginning of a long function, the entire function got verified 2^N times, not great.
I rewrote it instead as `assume(mem(x, cons(a, cons(b, nil))));`, which doesn't fork, and has the same meaning assuming `a` and `b` are side-effect-free. If `a` and `b` are just Boolean expressions, this also works with the implicit `x` being `true`.

Perhaps this is worth doing automatically?

**Comment by btj** [comment]
It's not clear that passing a disjunction to the SMT solver always performs better than forking in the symbolic execution engine. Especially so in the case of Redux, which performs poorly on SAT problems.

The user can easily choose the alternative behavior, either using the rewrite you propose, or simply by writing `assume((x == a || x == b) == true);`.

So I'm closing this as wontfix, but feel free to reopen.
