### ISSUE TITLE
Identifier interpretation in ghost code

### ISSUE THREAD

**Issue by bcip** [verifast/verifast#186]
> I updated this issue with a shorter example.

I define a C function `foo` and its corresponding pure function also called `foo`. When using pure function `foo` in loop invariant, it's OK. When using `foo` as an argument of a lemma (a ghost function call), VeriFast raises a typecheck error. I don't think it should happen, because ghost code shouldn't call any C functions and `foo` in argument of a lemma should be interpreted as the pure function `foo`. I am wondering whether it is a bug or a feature?

```
#include <stdio.h>

/*@
fixpoint int foo(int a, int b) {
  return a+b;
}
@*/

void foo(int *p, int *q)
//@requires *p |-> ?a &*& *q |-> ?b;
//@ensures *p |-> foo(a, b) &*& *q |-> b;
{
  *p += *q;
  for(int i = 0; i < 10; i++)
  //@invariant *p |-> foo(a, b) &*& *q |-> b;
  {
    //@mul_mono_l(a, b, foo(a, b));
  }
}
```

**Comment by jpdoyle** [comment]
While this change may be possible, there are good reasons for `foo` to refer to the C function, since you sometimes need to refer to it in annotations -- see the usage of `ackermann_iter` in https://github.com/verifast/verifast/blob/b7f6176557b89e28cd2c2b2a5fde350531128395/examples/termination/ackermann.c

**Comment by bcip** [comment]
@jpdoyle I see. This is an interesting example. We cannot call a C function in ghost code, but we can refer to it like a function pointer or so. Does it mean we not only want to refer to C functions in ghost statements but also in funcspecs and loop invariants?

**Comment by btj** [comment]
@bcip: Yes, we may need to refer to (the address of) a C function anywhere. So I'm closing this as NOTABUG for now.
