### ISSUE TITLE
Currying in VeriFast

### ISSUE THREAD

**Issue by bcip** [verifast/verifast#187]
I am trying to write a term like `map (+N) l` where `l` is a list of integers. I would like to use built-in `map` function because it comes with useful lemmas. So I would like to write a function `fun x => x+N`. I didn't find a way to do so, when`N` is a variable, not a constant. Is there any workaround?

**Comment by btj** [comment]
```c
/*@

fixpoint int plus(int x, int y) { return x + y; }

fixpoint list<int> example(int N, list<int> l) { return map((plus)(N), l); }

@*/
```

**Comment by bcip** [comment]
Thanks, Bart!
