### ISSUE TITLE
static double not being correctly parsed (Java)

### ISSUE THREAD

**Issue by andreffrosa** [verifast/verifast#194]
There is a problem while parsing doubles (and floats) when using the modifier "static". 
Example:

public class A {
    private static double a = 1.0; // Type mismatch. Actual: real. Expected: double.
    double b = 1.0; // OK
}

**Comment by btj** [comment]
You will now get a different error message :-)

Support for static field initializers is currently very limited. There is some support for constants (static final fields whose initializer is a literal expression) but it does not yet support floating-point numbers. Just let me know what you need exactly.
