### ISSUE TITLE
Unsoundness: evaluating `%` on constants disagrees with `div_rem`

### ISSUE THREAD

**Issue by jpdoyle** [verifast/verifast#196]
(inspired by an offhand comment in https://github.com/verifast/verifast/issues/195)
The following verifies:
```
void foo()
    //@ requires true;
    //@ ensures false;
{
    //@ div_rem(-5,-3);
}
```

**Comment by btj** [comment]
Good catch. This verifies as well:
```c
void foo()
    //@ requires true;
    //@ ensures true;
{
    //@ assert -5 % -3 == 1;
}
```

**Comment by btj** [comment]
VeriFast translates `-5 % -3` into an SMT solver term using `Proverapi.mk_mod`.

[Redux](https://github.com/verifast/verifast/blob/ff47420cbd6b4dd419153b48d6bc644e7d1b35a5/src/redux.ml#L861) implements `mk_mod` using `Num.mod_num`, which apparently uses the regular mathematical definition of quotient and remainder: `Num.mod_num (Num.num_of_int (-5)) (Num.num_of_int (-3))` evaluates to `1`.

`z3v4dot5prover.ml` turns `mk_mod` into an application of an uninterpreted function symbol, so this unsoundness happens only when using Redux (which is the default).

BTW: the treatment of division is unsound as well (again, only when using Redux, for the same reason). This verifies:
```c
void foo()
    //@ requires true;
    //@ ensures true;
{
    //@ assert -5 / -3 == 2;
}
```
