### ISSUE TITLE
Java code with data-race is accepted

### ISSUE THREAD

**Issue by jdmota** [verifast/verifast#209]
Unless I missed something, the following example includes a data-race that VeriFast does not detect, accepting the code while it should not.

The example includes an item that holds an integer value, which is updated from zero to one with the `changeState` method. Two threads are initialized and both have a reference to the item. Since the second thread is started before waiting for the first to finish, this would constitute a data-race, since both threads are modifying the item.

The thread implementation is adapted from [https://people.cs.kuleuven.be/~bart.jacobs/verifast/examples/java/ThreadRun.java.html](https://people.cs.kuleuven.be/~bart.jacobs/verifast/examples/java/ThreadRun.java.html) but using the `java.lang.Thread` seems to present the same issue (btw, the `Thread` class defined in the `java.lang.spec` file does not include the `join` method, but I imagine that is another issue).

I ran this example with VeriFast 19.12 IDE. Expected an error but zero were reported.

```java
//@ predicate Item(Item i; int state) = i.state |-> state;

class Item {
  private int state = 0;

  public void changeState()
    //@ requires Item(this, 0);
    //@ ensures Item(this, 1);
  {
    state = 1;
  }
}

//@ predicate started(MyThread t);

class MyThread {

  private Item item;

  //@ predicate pre() = this.item |-> ?i &*& i != null &*& Item(i, 0);
  //@ predicate post() = this.item |-> ?i &*& i != null &*& Item(i, 1);

  public MyThread(Item i)
    //@ requires i != null &*& Item(i, 0);
    //@ ensures pre();
  {
    this.item = i;
  }

  void start()
    //@ requires pre();
    //@ ensures started(this);
  {
    throw new RuntimeException("null");
  }

  void run()
    //@ requires pre();
    //@ ensures post();
  {
    item.changeState();
  }

  void join()
    //@ requires started(this);
    //@ ensures post();
  {
    throw new RuntimeException("null");
  }

}

public class Main {
  public static void main(String args[]) {
    Item item = new Item();

    MyThread t1 = new MyThread(item);
    t1.start();
    
    MyThread t2 = new MyThread(item);
    t2.start();

    t1.join();
    t2.join();
  }
}
```

**Comment by btj** [comment]
You forgot to specify a contract for `main`. Methods that do not have a contract are ignored by VeriFast. Just add
```java
//@ requires true;
//@ ensures true;
```
to fix the issue.

However, it is a bug that this is not easy to spot. I fixed it just now in https://github.com/verifast/verifast/commit/1c0722da7ad43402914df42551e8fdd305c11bb8 . `vfide` now shows statement execution counts in the margin.

**Comment by jdmota** [comment]
I did not know about that detail. Thank you so much!
