### ISSUE TITLE
Vfide crashes when using UINTPTR_MAX in an #if with a 64-bit target

### ISSUE THREAD

**Issue by SolalPirelli** [verifast/verifast#213]
Given a file `x.c` with the following contents:

```c
#if UINTPTR_MAX == 0
#endif
```

then on my Windows laptop running `vfide.exe x.c -target Linux64` and clicking on the "run" button causes a crash `VeriFast internal error: Failure("int64_of_big_int")`.

However, using `-target 32bit` works fine, and `verifast.exe x.c -target Linux64 -shared` works fine as well (!).

**Comment by btj** [comment]
Running with environment variable `OCAMLRUNPARAM=b` (for "backtrace") reveals that the exception is thrown at https://github.com/verifast/verifast/blob/b02e46f7e5f116c048d631e031a6be3811faa3d4/src/lexer.ml#L994 . The VeriFast preprocessor incorrectly uses signed 64-bit integers to evaluate preprocessor expressions; on a 64-bit platform, `UINTPTR_MAX` is outside of the range of the signed 64-bit integers.

It fails with `verifast.exe`, too: `verifast -target Linux64 issue213.c` raises the same exception. Apparently, command-line options take effect only when verifying files that appear later on the command line.
