### ISSUE TITLE
Unable to run verifast on MacOS

### ISSUE THREAD

**Issue by markrtuttle** [verifast/verifast#231]
Is this a familiar problem?

I'm unable to run vfide on MacOS.  I get a warning about not being about being able to find a symbol `_objc_opt_class`.  The expected file `/usr/lib/libobjc.A.dylib` does exist.  The referring filename includes the string "gtk" and "quartz."  I do have gtk+2 and gtk+3 and XQuartz installed and have upgraded to the latest versions.  

I can run vfide over ssh on a linux workstation.  I'd prefer to run it locally on my laptop.

Thanks,
Mark

```
laptop:~/verifast/bin ./vfide
2021-04-01 12:39:01.367 vfide-core[13522:85794] *** WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead. 
dyld: lazy symbol binding failed: Symbol not found: _objc_opt_class
  Referenced from: /Users/mrtuttle/verifast/bin/../lib/libgdk-quartz-2.0.0.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libobjc.A.dylib

dyld: Symbol not found: _objc_opt_class
  Referenced from: /Users/mrtuttle/verifast/bin/../lib/libgdk-quartz-2.0.0.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libobjc.A.dylib

./vfide: line 8: 13522 Abort trap: 6           "$MYABSDIR/vfide-core" "$@"
```

```
laptop:~/verifast/bin brew info gtk+
gtk+: stable 2.24.33 (bottled), HEAD
```

```
laptop:~/verifast/bin brew info gtk+3
gtk+3: stable 3.24.28 (bottled)
```

**Comment by btj** [comment]
Are you trying to run a binary package (if so: what version?) or are you building from source? Which macOS release are you on?

**Comment by btj** [comment]
Is it possible that your VeriFast working copy is on a shared disk shared with multiple versions of macOS? It seems the DLLs in your src/../lib directory expect newer versions of some system DLLs than you have on your machine.

Perhaps try zapping your src/../lib directory?

**Comment by markrtuttle** [comment]
I am running the 19.12 MacOS binaries from the release page on MacOS 10.14 laptop.  Is that too old?  

PS: I have installed some tools gtk 2 and 3 from homebrew and installed XQuartz.  It is possible that those installations have stomped on files related to Quartz.  I have not yet tried building from source, but I'll try that next.

**Comment by markrtuttle** [comment]
Building on MacOS 10.14 Mojave with the travis build scripts succeeds, but only if I remove existing installations of ocmal and make two minor changes to the build.  See below for the sequence of commands that works.  I've created a pull request https://github.com/verifast/verifast/pull/233 with the two changes in case that is useful.  

```
brew remove --force ocaml-findlib
brew remove --force ocaml-num
brew remove --force ocaml
rm -rf ~/.opam
sudo rm -rf /usr/local/vfdeps-0e0aebc
git pull
git clean -fdx .
git checkout .
sed -i.bak 's/! grep/- grep/' src/GNUmakefile
sed -i.bak 's/TRAVIS = "true"/{TRAVIS}x = "truex"/' setup-build.sh
./setup-build.sh
./build.sh > /tmp/verifast-build.txt 2>&1
```
