### ISSUE TITLE
commenting out a '\' with "//" crashes vf

### ISSUE THREAD

**Issue by rubenkindt** [verifast/verifast#251]
**Steps:**
opening fv using vfidedemo.bat
opening file (see below, I put the file in the tutorial folder)
commenting out a '\\' on line 7

**before:**
//@ensures account_balance(myAccount, balance) \\
	&*& result==balance;

**expected result:**
//@ensures account_balance(myAccount, balance) //\\
	&*& result==balance;

**actual result:**
windows error popup with
"Gtk-ERROR **: Byte index-2 is off the end of the line 
aborting.."

**file**
```c
#include "stdlib.h"
struct account {
    int balance;
};
int account_get_balance(struct account*myAccount)
//@requires account_balance(myAccount, ?balance);
//@ensures account_balance(myAccount, balance) \
	&*& result==balance;
{return myAccount->balance;}

int main()
//@requires true;
//@ensures b==5;
{ 
	struct account*myAccount = create_account();
	account_set_balance(myAccount, 5);
	int b = account_get_balance(myAccount);
	assert(b == 5);
	account_dispose(myAccount);
	return 0;
}
```

**Comment by anders-was-here** [comment]
Same result under Linux (verifast-21.04-44-g7ac51d5b).

```
(vfide:133849): Gtk-CRITICAL **: 09:59:45.967: _gtk_text_line_byte_locate: assertion 'byte_offset >= 0' failed
(vfide:133849): Gtk-ERROR **: 09:59:45.968: Byte index -2 is off the end of the line
```
