### ISSUE TITLE
malloc argument should not be of type int

### ISSUE THREAD

**Issue by jameshfisher** [verifast/verifast#27]
I think this is wrong: https://github.com/verifast/verifast/blob/6707c8be1a245a630ecc5c9eafef935ec8ed29c5/bin/malloc.h#L17

[The docs for `malloc`](http://linux.die.net/man/3/malloc) say

```
void *malloc(size_t size);
```

[I'm told that "size_t is an unsigned integer type"](http://stackoverflow.com/questions/2550774/what-is-size-t-in-c).

I can see the `requires` condition states `0 <= size`, but that's different. This should not fail:

```
#include <stddef.h>
#include <stdlib.h>

void foo()
//@ requires true;
//@ ensures true;
{
  size_t size = sizeof(int);
  malloc(size);
}
```

Currently it fails with

```
foo.c(9,10-14): Type mismatch. Actual: uintptr_t. Expected: int.
```

**Comment by btj** [comment]
Fixed by 416828da28324fb45b70b6ea75d06abbc0d3e116
