### ISSUE TITLE
Unexpected "No such type parameter"

### ISSUE THREAD

**Issue by jdmota** [verifast/verifast#271]
Hello,

When I verify the following example with VeriFast, I get this error in line 8: `No such type parameter, inductive datatype, class, interface, or function type:  T`.

Is this expected behavior?  I'm using VeriFast 21.04. Thanks in advance.

```java
//@ predicate node<T>(Node<T> node; T value) = node.value |-> value;

public class Node<T> {
  private T value;
  
  public Node(T value)
    //@ requires true;
    //@ ensures node<T>(this, value); // Error here
  {
    this.value = value;
  }
}
```

**Comment by btj** [comment]
Yes, this is expected behavior. Java generics and VeriFast generics are completely separate concepts. VeriFast simply erases Java type parameters before processing the annotations. So Java type parameters are not available in annotations. In annotations, simply use the raw type `Node`.

**Comment by jdmota** [comment]
That makes sense! Thank you very much for the detailed explanation!
