### ISSUE TITLE
Failing to import costum javaspec file

### ISSUE THREAD

**Issue by ajcostafct** [verifast/verifast#274]
I have a javaspec file with a class X. I placed it in bin/rt/ and added its name to rt.javaspec. When running vfide I get the No such type parameter, inductive datatype, class, interface, or function type: X and I notice that there is no window opened of that class inside the IDE.

**Comment by btj** [comment]
Funny. It works on my machine
<img width="882" alt="Schermafbeelding 2022-05-27 om 14 38 28" src="https://user-images.githubusercontent.com/1780310/170700848-2a725e47-909c-469b-a726-f06a357de02b.png">
<img width="882" alt="Schermafbeelding 2022-05-27 om 14 38 32" src="https://user-images.githubusercontent.com/1780310/170700859-2ed29913-8cd3-4aa7-8fa7-d626dd397d96.png">
.

**Comment by ajcostafct** [comment]
I changed to a nightly build and it also works. It did not work otherwise. @btj

**Comment by btj** [comment]
I'm closing as unreproducible for now. Feel free to reopen if you feel more action is needed.
