### ISSUE TITLE
When building Verifast in Linux Error: Unbound module Util

### ISSUE THREAD

**Issue by eleehiga** [verifast/verifast#277]
I am trying to build Verifast following https://github.com/verifast/verifast/blob/master/README.Linux.md. After running `setup-build.sh` I ran `export PATH=/tmp/vf-llvm-clang-build-aafd059/bin:$PATH` and `export PATH=/tmp/vfdeps-1c84e9a/bin:$PATH`. but when I run `make` this error appears: 
![image](https://user-images.githubusercontent.com/55113159/171179432-50027c3c-a18e-435b-a7bf-297135f8a990.png)

**Comment by eleehiga** [comment]
@btj That worked, thank you very much. Perhaps you should update the instructions with this.

**Comment by btj** [comment]
Done: daf4975bd105cba83432f2e553dfecfd278d79cc
