### ISSUE TITLE
What is `some` in Verifast?

### ISSUE THREAD

**Issue by eleehiga** [verifast/verifast#279]
Getting the error message `Cannot prove that 'printf_parse_format(cs, varargs)' is not an instance of constructor 'none'` for line `vfprintf(stderr, errstr, ap);`. In the error message and that context what is a `constructor`? Also, in the `requires` for the `vfprintf` prototype in `stdio.h` the function `some` is red and underlined. From that, I was wondering what is this function `some` and where can I find its definition (this is as there are also other functions that Verifast uses in which I cannot find the definition of)? Also here is the function as a whole where the error is appearing:
```
void
die(const char *errstr, ...)
	//@ requires string(errstr, ?cs);
	//@ ensures true;
{
	va_list ap;

	va_start(ap, errstr);
	vfprintf(stderr, errstr, ap);
	va_end(ap);
	exit(1);
}
```
And this is where the function `some` appears:
```
int vfprintf(FILE *file, char* format, va_list ap);
    /*@
    requires
        [?ff]file(file) &*& [?f]string(format, ?fcs) &*& va_list(ap, ?lastParam, ?apFrac, ?args) &*& printf_parse_format(fcs, args) == some(?ps) &*&
```
Finally can you guys please help me to solve this error message I am getting as presented in the first sentence of this issue? Thank you.

**Comment by jpdoyle** [comment]
`some` and `none` are the constructors of `option<t>` (see https://github.com/verifast/verifast/blob/0b5c2871989d6789d23b5ad3fff95da8b310a331/bin/prelude_core.gh#L12)

i.e., any `option<t>` is either `none` or `some(x)`, for some `x` of type `t`.

**Comment by eleehiga** [comment]
@jpdoyle Thank you that makes more sense now.

**Comment by eleehiga** [comment]
Also to solve the error I had, I had to put the statement `//@ assume(printf_parse_format(cs, varargs) == some(nil));`. This would show how ps is equal to nil.

**Comment by jpdoyle** [comment]
> Also to solve the error I had, I had to put the statement `//@ assume(printf_parse_format(cs, varargs) == some(nil));`. This would show how ps is equal to nil.

Just as a heads-up, that adds the assumption that your format specifier is well-formed and there are no `%s` format specifiers in `cs`, so your verification will be unsound for a call such as `die("%d")` and `die("%s","hello");`. Generally the best practice is to add assumptions as precondition in the `requires` clause rather than just adding `assume()` calls.

**Comment by eleehiga** [comment]
@jpdoyle Thank you I will think of another method to fix this error then and also thank you as I will try to do that best practice.
