### ISSUE TITLE
Error message `Expressions of type 'double' are not yet supported as arguments for a varargs function.`

### ISSUE THREAD

**Issue by eleehiga** [verifast/verifast#284]
Was wondering if you guys can please add support for this error message: `Expressions of type 'double' are not yet supported as arguments for a varargs function`. This is as I want to try verify the line (in https://github.com/clamiax/snore/blob/master/snore.c) `printf("%.*f%c%s", symbols[i].precision, piece, symbols[i].sym, i ? " " : "");` where piece is declared by `double piece;`.

**Comment by btj** [comment]
Fixed by https://github.com/verifast/verifast/commit/b3b0db56021cbe3eadf7685329d94185873c757b

**Comment by eleehiga** [comment]
@btj Thank you very much for fixing this.
