### ISSUE TITLE
Where is `//@ close_module();` declared in Verifast

### ISSUE THREAD

**Issue by eleehiga** [verifast/verifast#285]
I am having trouble with doing `close_module()` after `open_module()` and some operations. Therefore I was wondering where I can find the definition of `close_module` in Verifast?

**Comment by jpdoyle** [comment]
`close_module` and `open_module` are special statements handled by VeriFast, and their implementations are within the symbolic interpreter itself: https://github.com/verifast/verifast/blob/899dfae5e471c6e231168661f356f6dbf8b361e4/src/verifast.ml#L654

What error does VeriFast give you?

**Comment by eleehiga** [comment]
@jpdoyle Ah I see, when I do `open_module()` outputted to the symbolic heap is `chars((symbols+(4*struct_symbol_t_size)),(0*struct_symbol_t_size),elems)`. But after some operations that do not change that chars chunk, when I do `close_module()` there is the error `No matching heap chunks: chars(symbols, (struct_symbol_t_size * 4), _)`.

**Comment by jpdoyle** [comment]
oh, funky. So the thing that happened is that `verifast` automatically converted `symbols` into a bunch of struct objects when you opened the module, but `close_module()` just wants a `chars`. You need to convert those back into `chars` with `open_struct` and then join them all into one array to get `close_module()` to work (I named your file `open_module_test.c`, hence the different module name):
```c
#include <math.h>
#include <stdlib.h>

typedef struct symbol_t {
	char sym;
	int mult;
	int precision;
} Symbol;

/* must be in ascending order */
static Symbol symbols[] = {
	/* symbol  multiplier  precision */
	{ 's',     1,          3 }, /* first is default (if no suffix) */
	{ 'm',     60,         0 },
	{ 'h',     3600,       0 },
	{ 'd',     86400,      0 }, /* last is default (if no arguments) */
};

int
main(int argc, char **argv) //@ : main_full(open_module_test)
    //@ requires module(open_module_test, true) &*& 0 <= argc &*& [?f]argv(argv,argc,_); //&*& pointer(argv, _);
    //@ ensures module(open_module_test, false); 
{
    //@ open_module();
    //@ open_struct(&symbols[3]);
    //@ open_struct(&symbols[2]);
    //@ open_struct(&symbols[1]);
    //@ open_struct(&symbols[0]);
    //@ chars_join((char*)&symbols[0]);
    //@ chars_join((char*)&symbols[0]);
    //@ chars_join((char*)&symbols[0]);
    //@ chars_join((char*)&symbols[0]);
    //@ close_module();
    //@ leak [_]argv(_,_,_);
    return 0;
}
```
If you run-to-line on `return 0` and step back through the execution, you'll see the struct-field heap chunks getting consumed and turned into `chars`, then the `chars` get stitched together into one big array.

**Comment by eleehiga** [comment]
@jpdoyle Wow very interesting thank you very much for helping me out with that. Very cool to see the process in the step back.

**Comment by eleehiga** [comment]
@jpdoyle When I do `//@ close_module();` it returns back `module(test, false)`. Do you have a way you would recommend me to turn it back to `module(test, true)`? This for if I wanted to call `open_module()` after `close_module()`.
```
#include "../bin/math.h" 
#include "../bin/stdlib.h"

typedef struct symbol_t {
	char sym;
	int mult;
	int precision;
} Symbol;

/* must be in ascending order */
static Symbol symbols[] = {
	/* symbol  multiplier  precision */
	{ 's',     1,          3 }, /* first is default (if no suffix) */
	{ 'm',     60,         0 },
	{ 'h',     3600,       0 },
	{ 'd',     86400,      0 }, /* last is default (if no arguments) */
};

int
main(int argc, char **argv) //@ : main_full(test)
    //@ requires module(test, true);
    //@ ensures module(test, false); 
{
    //@ open_module();
    //@ open_struct(&symbols[3]);
    //@ open_struct(&symbols[2]);
    //@ open_struct(&symbols[1]);
    //@ open_struct(&symbols[0]);
    //@ chars_join((char*)&symbols[0]);
    //@ chars_join((char*)&symbols[0]);
    //@ chars_join((char*)&symbols[0]);
    //@ chars_join((char*)&symbols[0]);
    //@ close_module();
    //@ open_module();
    return 0;
}
```

**Comment by jpdoyle** [comment]
the `true`/`false` indicates whether the module is in its initial state. I'm not sure that there's a way to reset a module soundly in general.

**Comment by eleehiga** [comment]
@jpdoyle Ah darn ok that makes sense, thank you

**Comment by eleehiga** [comment]
@btj I was wondering if you could please change Verifast such that it can open and close modules over and over again? Like
```
//@ open_module();
    //@ open_struct(&symbols[3]);
    //@ open_struct(&symbols[2]);
    //@ open_struct(&symbols[1]);
    //@ open_struct(&symbols[0]);
    //@ chars_join((char*)&symbols[0]);
    //@ chars_join((char*)&symbols[0]);
    //@ chars_join((char*)&symbols[0]);
    //@ chars_join((char*)&symbols[0]);
    //@ close_module();
    //@ open_module();
```
