### ISSUE TITLE
`char **test = malloc(` does not yield a pointer

### ISSUE THREAD

**Issue by eleehiga** [verifast/verifast#287]
Currently I am trying to verify:  
```
int main()
	//@ requires true;
	//@ ensures true;
{
	char **test = malloc(1*sizeof(char**)); // need the "1*" there
	*test = malloc(3*sizeof(char)); 
}
```
But there is an error with the line `*test = malloc(3*sizeof(char)); ` with the message `No matching heap chunks: pointer(test0, _)`. This line creates pointers fine: https://github.com/verifast/verifast/blob/4eab38defa57958df1c92f4ebbc5afd62264e926/tutorial_solutions/students.c#L39
Was wondering if you guys can please help me understand why my code does not create a pointer?

**Comment by btj** [comment]
You are neglecting the case where `malloc` fails and returns a null pointer.

**Comment by eleehiga** [comment]
@btj I understand thank you. And I apologize as I should have checked for that.
