### ISSUE TITLE
Error with accessing heap chunk for indexing an array

### ISSUE THREAD

**Issue by eleehiga** [verifast/verifast#289]
For the following code
```
#include "../bin/math.h" 
#include "../bin/stdlib.h"
#include "../bin/stdarg.h"
#include "../bin/stdio.h"
#include "../bin/string.h"

#define LENGTH(X)   (sizeof X / sizeof X[0])

typedef struct symbol_t {
	char sym;
	int mult;
	int precision;
} Symbol;

static Symbol symbols[] = {
	/* symbol  multiplier  precision */
	{ 's',     1,          3 }, /* first is default (if no suffix) */
	{ 'm',     60,         0 },
	{ 'h',     3600,       0 },
	{ 'd',     86400,      0 }, /* last is default (if no arguments) */
};

/*@
lemma void indexing_mult(int j);
	requires symbol_t_mult(symbols, _);
	ensures symbol_t_mult(symbols + sizeof(symbols[0].mult)/4 * j, _);
	
lemma void regular_mult(int j);
	requires symbol_t_mult(symbols + sizeof(symbols[0].mult)/4 * j, _);
	ensures symbol_t_mult(symbols, _);
@*/

int main() //@ : main_full(test)
	//@ requires module(test, true);
	//@ ensures module(test, false);
{
	//@ open_module();
	double endtm = symbols[LENGTH(symbols) - 1].mult;
}
```
I am getting the error message `No matching heap chunks: [_]symbol_t_mult((symbols + (struct_symbol_t_size * (/((struct_symbol_t_size * 4), struct_symbol_t_size) - 1))), _)`. According to this error message I thought it would be looking for `symbol_t_mult((symbols+(3*struct_symbol_t_size)),86400)` but that is not the case. Therefore I was wondering if you guys can please help me fix this error?

**Comment by jpdoyle** [comment]
If you parse out the expression:
```
(symbols +
 (struct_symbol_t_size *
  (/((struct_symbol_t_size * 4),
     struct_symbol_t_size)
   - 1
  )
 )
),
```
The `/(a,b)` expression is how VeriFast represents integer division `a/b`.
The problem you're running into is that verifast is looking for `symbol_t_mult` at address  `symbols + sizeof(symbol_t)*(((sizeof(symbol_t)*4)/sizeof(symbol_t)) - 1)`, which definitely is the same as `symbols + 3*sizeof(symbol_t)`, but VeriFast doesn't have a full algebra solver.

What you need is a way to prove that `(sizeof(symbol_t)*4)/sizeof(symbol_t) == 4`. You can do that with the following lemma:
```c
lemma void division_unique(int D, int d, int q, int r);
    requires d != 0 &*& abs(r) < abs(d) &*& abs(d*q) <= abs(D)
        &*&  D == d*q + r;
    ensures  q == (D/d) &*& r == (D%d);
```
Proving it is a good (but tricky!) exercise :) I can give you hints if you need some hints, or you can just take this as an axiom.

**Comment by eleehiga** [comment]
@jpdoyle Thank you. I understand from that lemma that you had to create an assumption that the `(sizeof(symbol_t)*4)/sizeof(symbol_t) == 4` is valid with your precondition that make sense and the post condition having that `==` for the quotient and remainder assumptions.
