### ISSUE TITLE
Support offsetof macro from stddef.h

### ISSUE THREAD

**Issue by eleehiga** [verifast/verifast#293]
When verifying https://gitlab.freedesktop.org/wayland/wayland/-/blob/main/src/wayland-server.c#L1611 which has `size = offsetof (struct sockaddr_un, sun_path) + strlen(s->addr.sun_path);`. There is a parse error with the keyword `struct`. Therefore was wondering if you guys could please support having the keyword `struct` in a function call?

**Comment by btj** [comment]
The following currently works in VeriFast:
```c
#define offsetof(T, f) ((uintptr_t)&((T *)0)->f)

struct foo {
  int x;
  int y;
};

void test()
  //@ requires true;
  //@ ensures true;
{
  struct foo myFoo = {10, 20};
  //@ integer_limits((int *)((void *)&myFoo + offsetof(struct foo, y)));
  int y = *(int *)((void *)&myFoo + offsetof(struct foo, y));
  assert(y == 20);
}
```

**Comment by eleehiga** [comment]
@btj Thank you, the `#define` line works. But how did you know to create that line that way?

**Comment by eleehiga** [comment]
@btj Sorry actually from talking with someone about this line I now understand that you are getting the address of field f relative to the nullptr at the start of the struct T.
