### ISSUE TITLE
`sizeof(struct ...)` in the symbolic heap creates `..._size * ..._size` to be twice

### ISSUE THREAD

**Issue by eleehiga** [verifast/verifast#295]
Currently I am trying to verify this code here: 
```c
#include "math.h" 
#include "stdlib.h"
#include "stdarg.h"
#include "stdio.h"
#include "string.h"

struct test_bar {
	char * gamma;
};

struct test_foo {
	struct test_bar *bar;
};

struct test_alpha {
	struct test_foo *foo;
};

struct test_beta {
	struct test_alpha alpha;
};

void test(struct test_beta *beta, int i)
	//@ requires test_alpha_foo(&beta->alpha, ?foo) &*& test_foo_bar(foo, ?bar) &*& test_bar_gamma(bar+sizeof(struct test_bar)*i, _);
	//@ ensures true; 
{
	struct test_alpha *alpha = &beta->alpha;
	char *gamma = alpha->foo->bar[i].gamma;
}
```
However there is the error: `No matching heap chunks: [_]test_bar_gamma((bar + (struct_test_bar_size * i)), _)`. But in the symbolic heap there is: No matching heap chunks: [_]test_bar_gamma((bar + (struct_test_bar_size * (struct_test_bar_size * i))), _)`. So therefore I was wondering if this having of  `struct_test_bar_size * (struct_test_bar_size` twice is a bug?

**Comment by jpdoyle** [comment]
If `p` has type `T*`, `p+i` is equivalent to the "raw" addition `p+sizeof(T)*i`. You can change to `bar + i` or `(void*)bar + sizeof(struct test_bar)*i` and it will work.

**Comment by eleehiga** [comment]
@jpdoyle Thank you that worked, and I understand the raw addition conversion but I was wondering how you knew to add the `(void*)`?

**Comment by jpdoyle** [comment]
Generally `void*` is considered a "raw pointer" and a lot of C programs use it for that. Although technically by the spec, addition on `void*` is not well-formed and you should really cast to `char*` for addition.

**Comment by eleehiga** [comment]
@jpdoyle Ah ok I understand thank you
