### ISSUE TITLE
Cannot make `enum` inside functions

### ISSUE THREAD

**Issue by eleehiga** [verifast/verifast#296]
Currently I am trying verify this code:
```c
#include "math.h" 
#include "stdlib.h"
#include "stdarg.h"
#include "stdio.h"
#include "string.h"

void test()
{
	enum test {FOO, BAR};
}
```
However there is a parse error with `;` but if I put the line `enum test {FOO, BAR};` outside of the function then everything verifies fine. Therefore was wondering if there is a bug with declaring `enum` inside functions?

**Comment by btj** [comment]
This is indeed not yet supported. Do you have an important use case for it?

**Comment by eleehiga** [comment]
@btj I do not have an important use case for it

**Comment by btj** [comment]
Then I'm going to close this as WONTFIX for now.
