### ISSUE TITLE
aarch64: embedded use of "x86intrin.h" and "__rdtsc" in "src/linux/caml_stopwatch.c"

### ISSUE THREAD

**Issue by stephengaito** [verifast/verifast#303]
"Fools rush in where angels fear to tread" :-(

I am attempting to get verifast running on a raspberry pi 4 8GB (aarch64)....

In the first instance I compiled directly on my raspberry pi 4 inside an ubuntu:focal (20.04) container using podman  (took a while to do llvm-clang.... but it is now done).

When I finally got to compile verifast itself, I encountered the fact that the `src/linux/caml_stopwatch.c` code uses the `x86intrin.h` header and more specifically the gcc `__rdtsc` builtin function to directly access the x86 time stamp counter....

(I *think* that this is the "only" direct x86-ism in the verifast code -- certainly everything else "compiles" ... )

I have found a couple of discussions on how to replace `__rdtsc` on aarch64 ([Fun with Timers and cpuid](https://cpufun.substack.com/p/fun-with-timers-and-cpuid) and [AArch64 Programmer's Guides: Generic Timer](https://developer.arm.com/-/media/Arm%20Developer%20Community/PDF/Learn%20the%20Architecture/Generic%20Timer.pdf?revision=c710e7a7-9f52-4901-8c9d-91b19f44f9c7)) so I suspect I *could* hack this bit of code to work....

Before I do this... **I have a question: what is the stopwatch "for"? How critical is the stopwatch to verifast? How sensitive is the stopwatch to the "exact" rate of "ticks"?** (note that the "Fun with timers" article suggests that `__rdtsc` is *not* very accurate).

**Comment by stephengaito** [comment]
If it helps anyone, the attached patch seems to fix this problem well enough to allow the system to compile ...

[caml_stopwatch.c.patch.txt](https://github.com/verifast/verifast/files/9241404/caml_stopwatch.c.patch.txt)

**Comment by btj** [comment]
The stopwatch code is irrelevant to VeriFast's correct operation; it is used only to provide the timings in the `-verbose` listings.

I created https://github.com/verifast/verifast/pull/306 from your patch. If you want to be properly recorded as the author, please create one yourself.
