### ISSUE TITLE
Local declaration of pointer to pointer to struct

### ISSUE THREAD

**Issue by rsaill** [verifast/verifast#310]
The following program produces the unexpected error

> No such variable, constructor, regular function, predicate, enum element, global variable, or module: e

```
typedef struct s {
  int data;
} s_data;

void foo(void)
//@ requires true;
//@ ensures true;
{
  s_data **e;
}
```
However if I replace `s_data **e;` with `struct s **e;` Verifast does not complain anymore.

This looks like a bug to me.

**Comment by btj** [comment]
Fixed by cf0f25da83f898b57e7853599e60c44fbbce49ef
