### ISSUE TITLE
Missing axiom for nested right shift

### ISSUE THREAD

**Issue by rsaill** [verifast/verifast#311]
I am trying to verify a function containing some constant expressions using bitwise shift operator.
A minimal example would be:
```
void foo()
//@requires true;
//@ensures true;
{
  unsigned int y =  ( (0u >> 0) << 0);
}
```
I get the error

> Potential arithmetic underflow. (Cannot prove <(<= 0 (shiftleft (shiftright 0 0) 0));(<= 0 (shiftleft8 (shiftright8 0 0) 0))>.)

Looking at the smtlib file generated using option `-prover z3v4.5+SMTLib`, it seems that no axiom is generated for the symbol shiftright thus z3 cannot conclude anything.

Note that there is no problem when the shift is not nested in the expression.

**Comment by btj** [comment]
Workarounds: either write
```c
void foo()
//@requires true;
//@ensures true;
{
  unsigned int x = 0u >> 0;
  //@ produce_limits(x);
  unsigned int y =  ( x << 0);
}
```
or write
```c
//@ #include <bitops.gh>

void foo()
//@requires true;
//@ensures true;
{
  //@ shiftright_def(0, Zsign(false), N0);
  unsigned int y =  ( (0u >> 0) << 0);
}
```
