### ISSUE TITLE
Error message: `Preciseness check failure: body does not fix output parameter 'v'.`

### ISSUE THREAD

**Issue by eleehiga** [verifast/verifast#316]
When verifying there is an error in `prelude.h` with the line `predicate integer_(void *p, int size, bool signed_; int v) = integer__(p, size, signed_, some(v));` that yields the error `Preciseness check failure: body does not fix output parameter 'v'.` Was wondering if you guys could please help me solve this error?

**Comment by btj** [comment]
Did you `git pull` without `cd src; make`?

**Comment by eleehiga** [comment]
@btj Yes that is what I did. Thank you, I should definitely build after the command `git pull`.

**Comment by eleehiga** [comment]
@btj after `git pull` it seems like right after running `cd src; make` (nor does `make clean; make depend; make` work) does not work and I always have to run `./setup-build.sh` and then follow the step "2. Make sure all dependencies are in your PATH. For example: export PATH=/tmp/vfdeps-$VERSION/bin:$PATH." Is it that I have do `./setup-build.sh`? Because, running that command takes a while for that to complete.

**Comment by btj** [comment]
What error message do you get?

**Comment by eleehiga** [comment]
@btj After running `cd src; make` I get the following errors:
```
make: ocamlfind: Command not found
make: ocamlfind: Command not found
  OCAML     tabhunter.ml
  MYSH      assignments/run_model_solutions
  OCAMLOPT  json_tests
/bin/sh: 1: ocamlfind: not found
make: *** [GNUmakefile:572: testsuite] Error 127
```

**Comment by btj** [comment]
`ocamlfind` is in the `bin` directory of the `vfdeps` package. It seems that that directory is not in your PATH. Can you check?

**Comment by eleehiga** [comment]
@btj I do have that directory in my path. Where do I find this directory in the `verifast` repo?

**Comment by btj** [comment]
I don't understand the question.

**Comment by eleehiga** [comment]
@btj Or is it that when I run `build.sh` I have to move `/tmp/vfdeps-$VERSION` to not the `tmp` folder? In general I am asking where do I find " the `bin` directory of the `vfdeps` package".

**Comment by btj** [comment]
Where did you extract the `vfdeps` package on your machine? `setup-build.sh` puts it in `/tmp` on Linux but while this works fine for CI builds, on your machine you will want to put it in a more permanent place.

**Comment by eleehiga** [comment]
@btj I left `vfdeps` in my `/tmp` folder and understand from what you said that I should put it in a more permanent place. Therefore, was wondering if you could please update the installation instructions telling the user to put `vfdeps` in a more permanent place.

**Comment by btj** [comment]
After looking more closely at this, my suggestion is wrong: `vfdeps` must be extracted into `/tmp` (or, as the instructions suggest, somewhere else but then you need to add a symlink from `/tmp/vfdeps-$VERSION` to that other place). I'm not sure how often a Linux distro will clean `/tmp` but after it does you need to recreate the symlink; perhaps you should add some code to your login script or to the script that you use to setup your VeriFast development shell to create the symlink if it doesn't exist. (I use MacOS myself.)

You could argue that we should build `vfdeps` into some other more permanent place. But `/tmp` is the only directory that is pretty much guaranteed to be writable for any Linux user. Unlike the MacOS case, Linux users are more likely to be using a shared machine for which they do not have admin access; we would like to support this.
