### ISSUE TITLE
Is there a way to prove that two `integer__`s with total fraction above 1 don't alias?

### ISSUE THREAD

**Issue by jpdoyle** [verifast/verifast#317]
I'm working on updating some code for the new `uninit` changes, and I'm struggling to prove the lemma:
```c
lemma void ullong__unique(unsigned long long *p);
    requires [?f]ullong_(p, ?v);
    ensures [f]ullong_(p, v) &*& f <= 1;
```

For `u_llong_integer` I can use `integer__unique`, but there isn't an equivalent for `integer__`.

**Comment by btj** [comment]
It may be missing. Feel free to submit a PR!
