### ISSUE TITLE
Deduction for nonlinear arithmetic is highly incomplete and brittle

### ISSUE THREAD

**Issue by necto** [verifast/verifast#37]
Here is a simplified code:

``` Ruby
/*@
  predicate valsp(void* values, list<int> vals) = true;

  fixpoint bool foo (void* x, void* a, void* b);

  lemma void glue_values(void* values, list<int> vals, int i,
                         int vsz, void* a, void* b)
  requires true == foo(values + i*vsz, a, b) &*&
           valsp(values+(i+1)*vsz, drop(i+1, vals));
  ensures true;
  {
    void* xxx = values + i*vsz;
    assert true == foo(xxx, a, b); //This assertion holds.
    switch(vals) {
      case cons(h,t):
        assert true == foo(xxx, a, b); //This assertion breaks;
      case nil:
    }
  }
  @*/
```

The lemma as it is does not make much sense, but it does not have to.
The first assertion repeats one of the preconditions, and trivially holds. But the second repetition of the same assertion (in the switch-> case cons body) suddenly does not hold anymore.
Why does this happen?

P.S. I observed, that it is important, to have this `valsp` predicate around, as without it the lemma verifies.
Also, it should have something to do with the `values + i*vsz` address calculation, as if I replace `xxx` with an arbitrary `void*` argument, it also passes.
The [`note`](https://github.com/verifast/verifast/issues/19#issuecomment-210546354) workaround does not help here.

**Comment by btj** [comment]
Yeah. I expect that this is due to the fact that SMT solvers generally, and both Z3 and Redux in particular, are highly incomplete and brittle in the presence of nonlinear arithmetic. (But Redux should be slightly better-behaved; which solver did you use?)

Perhaps it's best to completely avoid multiplication (except when one of the operands is a literal) by replacing it with a predicate like

```
predicate mul(int a, int n; int b) = n == 0 ? b == 0 : mul(a, n - 1, ?b0) &*& b == b0 + a;
```

You might need some lemmas to convert between `*` and `mul`, and for some properties of `mul`.

An alternative is the following:

```
fixpoint int mul(int a, int n);

lemma_auto void mul_zero(int a);
    requires true;
    ensures mul(a, 0) == 0;

lemma void mul_succ(int a, int n);
    requires true;
    ensures mul(a, n + 1) == mul(a, n) + a;
```

**Comment by necto** [comment]
Another workaround for this particular case is to wrap the statement into a predicate:
```Ruby
/*@
  predicate valsp(void* values, list<int> vals) = true;

  fixpoint bool foo (void* x, void* a, void* b);


  predicate keep_foo(void* x, void* a, void* b) =
    true == foo(x, a, b);


  lemma void glue_values(void* values, list<int> vals, int i,
                         int vsz, void* a, void* b)
  requires true == foo(values + i*vsz, a, b) &*&
           valsp(values+(i+1)*vsz, drop(i+1, vals));
  ensures true;
  {
    void* xxx = values + i*vsz;
    assert true == foo(xxx, a, b);
    close keep_foo(xxx, a, b);
    switch(vals) {
      case cons(h,t):
        open keep_foo(xxx, a, b);
        assert true == foo(xxx, a, b);
      case nil:
    }
  }
  @*/
```

**Comment by btj** [comment]
Thanks to 948a7d1, the snippet now verifies as-is. (Just eliminate the leak error by putting `ensures valsp(_, _);`.)
