### ISSUE TITLE
can't open struct with fixed-size array

### ISSUE THREAD

**Issue by farmerzhang1** [verifast/verifast#376]
```c
struct rec {
    char array[10];
};

int testf (struct rec* p)
//@ requires p->array |-> ?arr;
//@ ensures true;
{
    //@ open rec_array(p, arr);
    return 0;
}
```
when I want to open `rec_array(p, arr)`, VeriFast says `No such predicate instance`

**Comment by btj** [comment]
This is as designed. VeriFast generates field chunk predicates only for fields of "primitive" type, i.e. not array or struct type. To access the elements of `p->array`, your precondition should read `p->array[..10] |-> ?elems` which is equivalent to `chars(p->array, 10, ?elems)`.
