### ISSUE TITLE
[feature request] Dereferencing pointers of type uint16 is not yet supported.

### ISSUE THREAD

**Issue by necto** [verifast/verifast#42]
How difficult would it be to support pointers to uint16_t ?
```C
#include <stdint.h>

int main()
//@ requires true;
//@ ensures true;
{
  uint16_t x = 1;
  uint16_t *xp = &x;
  return 0;
}
```

**Comment by btj** [comment]
See https://groups.google.com/forum/#!topic/verifast/grGwdUnK4BU

**Comment by necto** [comment]
Cool! That was easy, thank you. Should I do a pull request for this patch https://github.com/necto/verifast/commit/f75187fb28d60c4758e9260f81c8ef8ba7725c76 ?

**Comment by btj** [comment]
Yes, that'd be great. But please see my line comment for the typo. And I suggest to rename `(u)shortp` to `(u)short_integer` for uniformity with the existing pointee predicates. (Remember that you can use the `*x |-> v` syntax, so the length of the name is not a problem.) (`shorts` is fine, though.)
