### ISSUE TITLE
Z3 support?

### ISSUE THREAD

**Issue by necto** [verifast/verifast#48]
Hello,
The linux install how-to https://github.com/verifast/verifast/blob/master/README.Linux.md
Mentions the possibility to build VeriFast with Z3 solver instead of Redux. Unfortunately the Z3 distribution link is private (hidden behind Kuleuven login page).

What version of Z3 does VeriFast support, and how can external users use it with Z3?

**Comment by btj** [comment]
Commit 1b8f8da81bd0373b5f469ca3e39eb6ddc89f6162 adds support for the current, open source version of Z3.

**Comment by necto** [comment]
Just tried that out: it works! Thank you.
