### ISSUE TITLE
How to prove `0 < x => 0/x == 0` ?

### ISSUE THREAD

**Issue by necto** [verifast/verifast#51]
Where can I find the list of arithmetic axioms to deduce such equalities?

**Comment by btj** [comment]
Here's a proof:
```c
/*@

lemma void mul_mono(int a1, int a2, int b)
    requires a1 <= a2 &*& 0 <= b;
    ensures a1 * b <= a2 * b;
{
    for (int i = 0; i < b; i++)
        invariant i <= b &*& a1 * i <= a2 * i;
        decreases b - i;
    {}
}

@*/

void to_verify(int x)
/*@ requires 0 < x; @*/ 
/*@ ensures true; @*/
{
   //@ div_rem(0, x);
   //@ if (0 / x <= -1) { mul_mono(0 / x, -1, x); }
   //@ if (1 <= 0 / x) { mul_mono(1, 0 / x, x); }
   //@ assert 0/x == 0;
}
```
List of axioms:
- The SMT solver is complete for linear arithmetic (i.e. arithmetic not involving multiplication (except for multiplication by a literal)), and for theorems for which multiplications can be treated as uninterpreted function symbols.
- Multiplication is fully defined by the equations `x * 0 == 0` and `x * (y + 1) == x * y + x` and `x * (y - 1) == x * y - x`, which the SMT solver can prove. Combined with induction on the integers (using loops), you can prove any theorem.
- Division is fully defined by the `div_rem` lemma in `prelude.h`.

**Comment by necto** [comment]
Thank you!
