### ISSUE TITLE
Parse error for `struct` initialization of `{ 0 }`

### ISSUE THREAD

**Issue by thanhtoantnt** [verifast/verifast#510]
When a `struct` variable is initialized using `{ 0 }`, for example, `struct struct_type struc_var = { 0 }`, VeriFast shows an error: `Length of initializer list does not match number of struct fields.` 

I can temporarily fix this problem by initializing all the fields, e.g., ` { 0, 0, 0}` for a `struct` data structure having three fields. However, I have another problem when one field is an array of integers that I don't know how to initialize it such that VeriFast can handle.

**Comment by btj** [comment]
Use a nested initializer list? `{ 0, { 0 }, 0 }`

**Comment by thanhtoantnt** [comment]
I tried that and got the error: `Type mismatch. Actual: list<int>. Expected: uint8_t[8].` because the field is an array

**Comment by thanhtoantnt** [comment]
Thank you very much.
