### ISSUE TITLE
VeriFast "forgets" loop invariant on loop exit.

### ISSUE THREAD

**Issue by necto** [verifast/verifast#52]
Here is the code snipped that does not work:

```Ruby
/*@
  lemma void mod_rotate(int a, int b);
  requires 0 <= a &*& 0 < b;
  ensures true == ((a+b)%b == a%b);

  lemma void mod_injection_minus_n(int k, int capacity, int n)
  requires 0 <= k &*& 0 < capacity &*& 0 <= k + n*capacity &*& n < 0;
  ensures true == (((k + n*capacity) % capacity) == k%capacity);
  {
    int i = n;
    for (i = n; i < 0; ++i)
    invariant true == ((k + i*capacity)%capacity == (k + n*capacity)%capacity) &*&
              0 <= k + i*capacity &*&
              i <= 0;
    decreases -i;
    {
      mod_rotate(k + i*capacity, capacity);
      assert true == ((k + i*capacity)%capacity == (k + n*capacity)%capacity);
    }
    //assume(((k + i*capacity)%capacity) == (k + n*capacity)%capacity);//workaround
    assert true == ((k + i*capacity)%capacity == (k + n*capacity)%capacity);
  }
@*/
```
VeriFast rejects the last assertion. However, in the VFIDE I can see exactly the same formula in the assumption list. If you uncomment the `assume` statement with the same formula, the assertion passes.

**Comment by btj** [comment]
This is due to the fact that variable `i` gets incremented, and as a result, its value at the end of the loop iteration is different from the symbol `i`, which represents the value of variable `i` at the start of the loop iteration. The names you see in the assumptions list refer to symbols, not variables.

**Comment by necto** [comment]
Which assertion should hold at the end of the loop then?
These two (with the expected exit value of `i` -- `0` and with a reference to a "previous" value (`i-1`)) do not hold either:

```Ruby
    assert true == ((k + (i-1)*capacity)%capacity == (k + n*capacity)%capacity);
    assert true == ((k + 0*capacity)%capacity == (k + n*capacity)%capacity);
```

**Comment by necto** [comment]
Moreover, when I compare the VeriFast reported error:
```
Assertion might not hold: true <==> %((k + (i * capacity)), capacity) = %((k + (n * capacity)), capacity)
```
with the assumption listed:
```
true <===> %((k + (i * capacity)), capacity) = %((k + (n * capacity)), capacity)
```
I see no difference.
Does one of them refer to a variable `i` and another to a symbol `i`?

**Comment by btj** [comment]
Yes.

You can see the mapping between variables and symbols (more specifically, the current symbolic value (a term involving symbols, literals, and operators) of each variable) in the Locals pane on the right-hand side of the VeriFast IDE window.

**Comment by btj** [comment]
Oops. Hold on; I may have jumped to conclusions too quickly. Let me investigate more closely.

My guess is now that your problem is due to the presence of multiplication.

**Comment by btj** [comment]
Never mind my comments about variables versus symbols; those are wrong.

I confirmed that the problem is due to the brittleness of SMT solvers when dealing with nonlinear multiplication. The solution is sometimes to hide the multiplication, and replace it by an uninterpreted function symbol. The following verifies:
```
/*@
lemma void mod_rotate(int a, int b);
    requires 0 <= a &*& 0 < b;
    ensures true == ((a+b)%b == a%b);

fixpoint int mul(int x, int y);

lemma void mul_def(int x, int y);
    requires true;
    ensures mul(x, y) == x * y;

lemma void note(bool b);
    requires b;
    ensures b;

lemma void mod_injection_minus_n(int k, int capacity, int n)
    requires 0 <= k &*& 0 < capacity &*& 0 <= k + n*capacity &*& n < 0;
    ensures true == (((k + n*capacity) % capacity) == k%capacity);
{
    int i = n;
    mul_def(i, capacity);
    for (i = n; i < 0; ++i)
        invariant
            true == ((k + mul(i, capacity))%capacity == (k + mul(n, capacity))%capacity) &*&
            0 <= k + mul(i, capacity) &*&
            i <= 0;
        decreases -i;
    {
        mul_def(i, capacity);
        mul_def(n, capacity);
        note(true == ((k + i * capacity)%capacity == (k + n*capacity)%capacity));
        note(0 <= k + i*capacity);
        mod_rotate(k + i*capacity, capacity);
        assert true == ((k + i*capacity)%capacity == (k + n*capacity)%capacity);
        mul_def(i + 1, capacity);
    }
    mul_def(i, capacity);
    mul_def(n, capacity);
    //assume(((k + i*capacity)%capacity) == (k + n*capacity)%capacity);//workaround
    assert true == ((k + i*capacity)%capacity == (k + n*capacity)%capacity);
  }
@*/
```

**Comment by necto** [comment]
This works. Just a nit. There is no definition (and I guess no correct and working way to provide one) for `mul_def`. So `verifast modulo.c` fails:
```
Module 'modulo.vfmanifest': unsatisfied requirement './modulo.c#mul_def'.
```

Anyway, thank you for the plausible workaround.
