### ISSUE TITLE
Improve typechecking of shift operators

### ISSUE THREAD

**Issue by Bromind** [verifast/verifast#59]
Hi, 

concerning the support for long long, I am wondering wether it is possible to change "int_size" to 8 in ./src/ast.ml. Do you know if that would cause problems concerning promotion (int should not be promoted to long long int) ? Or if it is better to create a longType (similar to intType, cf. ast.ml:100). 

I tried the first solution locally, it seems to solve problems such as ">>" (shiftright) not been defined for int64, but I don't know wether it is correct w.r.t. some semantic corner-cases.

**Comment by btj** [comment]
Fixed by fa443e583dbc0ebf55170b3f3a2c5f617c0ded1d
