### ISSUE TITLE
tree traversal with arbitrary number of children

### ISSUE THREAD

**Issue by etiennebirling** [verifast/verifast#639]
Hello,
I am currently trying to produce a function traversing a kind of AST to convert it into another AST (I skip the details about the exact context, which would make it even more complex).
Concretely, I'm given an AST with nodes of type nodeIn, and I would like to convert it into an AST of type nodeOut, using some of the most basic recursions.
```
/*@
inductive nodeIn = parentIn(list<nodeIn>) | leafIn;
inductive nodeOut = parentOut(list<nodeOut>) | leafOut;
fixpoint nodeOut getOut(nodeIn n){
    switch(n){
        case parentIn(l): return parentOut(map(getOut, l));
        case leafIn: return leafOut;
    }
}
@*/
```
However, while this worked when manually applying the recursion on a bounded number of children per parent node (for instance for a binary tree with ≤ 2 children per parent), Verifast complains when the recursion is abstractly mapped (using the map statement) to all children of a parent.
Is there somehow a way to represent such a behavior in Verifast, or should I change something in my type structure to me able to recursively traverse it?

Thanks in advance for your help,

**Comment by btj** [comment]
We had the same problem [here](https://github.com/verifast/verifast/blob/master/bin/rust/mask.rsspec): we axiomatised the function. I don't think there is currently another way to do it.

**Comment by btj** [comment]
It might work if you add forestIn_nil and forestIn_cons constructors to type nodeIn, so that the recursion doesn't go through type `list`, but then you get junk in your `nodeIn` type (and in your forestIn type).

**Comment by btj** [comment]
Your particular example can easily be supported by special-casing `map` calls in the fixpoint termination checker. I will do so.

**Comment by etiennebirling** [comment]
Ok, thank you for your answers. 
May I ask if you plan on applying your last suggestion soon? I don't really depend of it (in the sense that I have alternative ways of implementing my thing, especially by bounding the number of children per node), but if this update is released in the next few weeks, I could decide to go for the approach described above and orient all my work accordingly. So my decision will be impacted by yours in this case.
Best,

**Comment by btj** [comment]
Hi Etienne, Note that if you axiomatise your function for now, you can replace it with a proper definition later without impacting any client code. But in any case, I will try to implement this tomorrow.

**Comment by etiennebirling** [comment]
Thanks for your quick reply.
That's actually true, axiomatizing the function would actually solve the problem.
In my case however, this function is not absolutely necessary (in the sense that the result could be retrieved through another way) and mostly exists as syntactic sugar, so using a lemma every time in addition would remove a bit of the sugar.
But thanks for this idea, it will probably do it for the first weeks.

**Comment by btj** [comment]
Note that by declaring the lemma as an autolemma, it will be applied automatically. In any case, I've started implementing support for this definition, it should be finished today or tomorrow.
