### ISSUE TITLE
Arrays of (unsigned) long long

### ISSUE THREAD

**Issue by Bromind** [verifast/verifast#73]
Hi, 
I am trying to implement arrays of (unsigned) long long. On the current upstream, trying to access such an array leads to "Dereferencing array elements of type int64 is not yet supported". In the following, I only consider the signed case, but the same happen for unsigned long long.

I updated the `try_pointee_pred_symb0` method (~verifast1.ml:3919) with the `Int(Signed, 8)` case, <hich requires to add `llong_pointee_tuple` just above, and also to update `predinstmap1` around line 4370.

However, with those changes, when I try it, I got a `Not_found` exception, at line ~3884. After some search, it seems that the `predfammap` map does not contain a `malloc_block_llongs`. However, I don't really get how this map is built, and then I don't really understand how to add the missing stuff. 

Any idea ?

[The modifications I'm talking about are visible here: https://github.com/Bromind/verifast/commit/ff168cfafae59f9f23f60d3088dc58a8d52b068c ]

**Comment by btj** [comment]
You have to define a predicate `malloc_block_llongs` in `prelude.h`.

**Comment by necto** [comment]
Does #74  close the issue?
