### ISSUE TITLE
Auto open on reading

### ISSUE THREAD

**Issue by JoergPfaehler** [verifast/verifast#76]
Is it possible to perform auto open/close upon dereferencing of pointers for reading? A simplified example would be:
```
#include <stdlib.h>
/*@
  predicate pred(int* p; int x) = integer(p, x);
@*/
void f()
  //@requires true;
  //@ensures true;
{
  int* p = malloc(sizeof(int));
  if (p == 0) return;
  //@close pred(p, _);
  int i = *p; // Does not work, but "*p = ..." would work
  free(p);
}
```
In the example the read *p does not lead to an attempt to auto open pred, but a write of *p would. Is it (easily) possible to add auto open/close for read accesses or is there another way to achieve the same thing (in the form of a lemma for pred e.g.)? Or is this restriction to only auto open on write accesses on purpose?
Note that chunk transformation lemmas, such as
```
/*@
  lemma_auto void foo()
    requires pred(?p, ?x);
    ensures integer(p, x); { }
@*/
```
do not seem to work either in this context.

An additional question: is it possible to define predicates that should always be expanded as soon as they are produced (in this case and in some others that would be what I "actually" want)?

**Comment by btj** [comment]
Fixed by df864f78f10c92b6c19f55ae41276ba9d31eb3ef.

(For auto-expanded predicates, please open a separate issue if necessary.)
