### ISSUE TITLE
Z3 is now MIT licensed

### ISSUE THREAD

**Issue by jbapple** [verifast/verifast#78]
https://github.com/verifast/verifast/blob/master/Z3.LICENSE.txt can be replaced with https://github.com/Z3Prover/z3/blob/master/LICENSE.txt

**Comment by btj** [comment]
The problem is that VeriFast uses the very old Z3 version 1.3.6, and it's not clear that the new license applies to this old binary release as well.

**Comment by btj** [comment]
Commit 1b8f8da81bd0373b5f469ca3e39eb6ddc89f6162 adds support for the current, MIT-licensed, version of Z3. Note: not yet enabled in the nightly builds.

**Comment by btj** [comment]
VeriFast now ships with Z3 4.5.0.
