### ISSUE TITLE
Strange behavior when typing list<pair<int, int> > with inlining head(...)

### ISSUE THREAD

**Issue by Bromind** [verifast/verifast#79]
Hello, 

I have a strange behaviour with the following example. The two fixpoints functions do the same thing, except one inline the `head` fixpoint.

None should type, as a `list<pair<int, int> >` is expected, and in the second case of the `switch(lst1)`, only a `pair<int, int>` is returned (namely, the head of the second list). While this doesn't type as expected when using the `head` fixpoint, the example inlined types.

```
/*@
#include <list.gh>
@*/

/*@

fixpoint list<pair<int, int> > example_inline(list<pair<int, int> > lst1, list<pair<int, int> > lst2) {
  switch(lst1){
    case nil: return nil;
    case cons(pair1, tail1): return {
      switch(lst2){
        case nil: return default_value<pair<int, int> >;
        case cons(pair2, tail2): return pair2; 
      }
    };
  }
}

fixpoint list<pair<int, int> > example_head(list<pair<int, int> > lst1, list<pair<int, int> > lst2) {
  switch(lst1){
    case nil: return nil;
    case cons(pair1, tail1): return head(lst2);
  }
}

@*/
```

[EDIT:] If the first example is updated to indeed return a `list<pair<int, int> >` in the second switch, verifast returns this error: "Type mismatch. Actual: list<pair<int, int>>. Expected: pair<int, int>."
```
fixpoint list<pair<int, int> > example_inline(list<pair<int, int> > lst1, list<pair<int, int> > lst2) {
  switch(lst1){
    case nil: return nil;
    case cons(pair1, tail1): return {
      switch(lst2){
        case nil: return nil;
        case cons(pair2, tail2): return cons(pair2, nil);
      }
    };
  }
}
```

**Comment by necto** [comment]
The problem comes from the extra `{}` block in the return expression.

**Comment by btj** [comment]
Indeed. Within ghost code, the expression `{ e }` denotes the list with the single element `e`.

**Comment by Bromind** [comment]
All right, I didn't know the `{ e }` specificity. Thanks.
