### ISSUE TITLE
Z3 loops forever

### ISSUE THREAD

**Issue by rafoo** [verifast/verifast#89]
On the following file, calling `verifast -shared -prover z3v4.5 -c bug.c` seems to take forever (I stoped it after 10 minutes). This might be a bug in Z3 itself since everything works fine with Redux. When calling with `-verbose 10`, the last line is `0.064000s: bug.c(42,8-19): Executing statement`. Line 42 is `take_append(lst, s1, s2);`.

File bug.c:

```
/*@
// From assoclist.gh

fixpoint list<t2> values<t1, t2>(list<pair<t1, t2> > map) {
  switch(map) {
    case nil: return nil;
    case cons(h, t): return cons(snd(h), values(t));
  }
}

lemma_auto void take_values<t1, t2>(int i, list<pair<t1, t2> > map);
  requires 0 <= i && i <= length(map);
  ensures take(i, values(map)) == values(take(i, map));

@*/

// Removing the previous take_values lemma solves the bug.

/*@
// From listex.gh

lemma void take_append<t>(int n, list<t> xs, list<t> ys);
  requires 0 <= n && n <= length(xs);
  ensures take(n, append(xs, ys)) == take(n, xs);

@*/

/*@

fixpoint list<t> extract<t>(list<t> s, int fst, int lst) {
    return take(lst-fst, drop(fst, s));
}

lemma void extract_append<t>(list<t> s1, list<t> s2, int fst, int lst)
requires 0 <= fst &*& fst <= lst &*& lst <= length(s1);
ensures extract(append(s1, s2), fst, lst) == extract(s1, fst, lst);
{
  switch(s1) {
    case nil:
    case cons(a, tl):
     if (fst == 0) {
       take_append(lst, s1, s2);
     } else {
       extract_append(tl, s2, fst-1, lst-1);
     }
  }
}

@*/
```

**Comment by btj** [comment]
This is probably a so-called matching loop. A matching loop is when the SMT solver keeps instantiating quantified axioms for new terms.

SMT solvers usually perform quantifier instantiation by means of triggers. That is, they identify a number of term patterns, called triggers, in the body of the quantifier. Then, whenever they encounter a term that matches one of the triggers of some quantified axiom, they instantiate that axiom for that term. However, the instantiation may lead to new terms being introduced, and therefore new triggers being matched, and new instantiations happening. This can get into an infinite loop.

To remedy this, try turning the autolemma into a regular lemma and applying it manually. Or, specify a trigger explicitly. For example:

```
lemma_auto(take(i, values(map)) void take_values<t1, t2>(int i, list<pair<t1, t2> > map);
```

If no trigger is specified explicitly, Z3 will detect triggers automatically. In this case, it will probably take both `take(i, values(map))` and `values(take(i, map))` as triggers.

I hardly ever use Z3 nowadays, so I have little experience debugging matching loops with recent Z3 versions, so I have no immediate further advice to offer there. There is probably a way to get it to print something to the console whenever it instantiates a quantifier.

**Comment by rafoo** [comment]
Thank you, adding the trigger solves the issue.
