### ISSUE TITLE
macOS build fails due to out-of-date Homebrew lablgtk bottle

### ISSUE THREAD

**Issue by btj** [verifast/verifast#91]
Reported to Homebrew as https://github.com/Homebrew/homebrew-core/issues/14126

**Comment by ilovezfs** [comment]
This should fixed now: https://github.com/Homebrew/homebrew-core/pull/14185.

**Comment by btj** [comment]
It is; the build now succeeds. Thanks!

**Comment by ilovezfs** [comment]
@btj you're welcome!
